languageCode = "en"
languageName = "English"
displayName = ":flag-uk:"
isoCode = "en"
weight = 1
rtl = false

title = "MH"
# logo = "img/logo.jpg"
description = "Portfolio Miguel Angel Huamán."
copyright = "&copy; 2023"

dateFormat = "2 January 2006"

[author]
  name = "Miguel Angel Huamán"
  image = "img/author.jpg"
  headline = "Author"
  bio = "Developer"
  links = [
    { twitter = "https://twitter.com/miguel1man/" },
    { linkedin = "https://linkedin.com/in/miguel1man/" },
    { github = "https://github.com/miguel1man/" }
  ]
